#!/usr/bin/env python

import matplotlib.style as s
s.use('seaborn')
from matplotlib.pyplot import subplots
from database import run_query
from pathlib import Path

build_dir = Path(__file__).with_name('build')

df = run_query('SELECT * FROM mapping.dem_reference')
dgps = df[df.type=='dgps']

## DGPS only

fig, ax = subplots()
dgps.error.hist(ax=ax, bins=100)

ax.set_xlim(-2,2)

fn = str(build_dir/'dgps-errors.pdf')
fig.savefig(fn)

## Theodolite and DGPS

fig, ax = subplots()
df.error.hist(by=df.type,ax=ax,
        bins=100, stacked=True)

ax.set_xlim(-2,2)

fn = str(build_dir/'error-comparison.pdf')
fig.savefig(fn)
