#!/usr/bin/env python

import matplotlib.style as s
s.use('seaborn')
from matplotlib.pyplot import subplots
from database import run_query
from pathlib import Path

file = Path(__file__)
build_dir = file.with_name('build')

df = run_query('SELECT * FROM mapping.dem_reference')
dgps = df[df.type=='dgps']

## DGPS only

fig, ax = subplots()
dgps.error.hist(ax=ax, bins=100)

ax.set_xlim(-2,2)
ax.set_ylabel("n measurements")
ax.set_xlabel("DGPS-DEM error (m)")

fn = str(build_dir/'dgps-errors.pdf')
fig.savefig(fn)

## Theodolite and DGPS
theodolite = df[df.type == 'theodolite']
fig, ax = subplots()
ax.hist([dgps.error, theodolite.error],
        bins=100, stacked=True, label=['DGPS','Theodolite'])

ax.legend()

ax.set_xlim(-2,2)
ax.set_ylabel("n measurements")
ax.set_xlabel("DEM error (m)")


fn = str(build_dir/'error-comparison.pdf')
fig.savefig(fn)
