#!/usr/bin/env python

import rasterio
from pathlib import Path
from os import getenv, path

project = Path(getenv('PROJECT_DIR'))

from database import run_query

# Get data from database for DGPS and theodolite
# as a pandas data table
dn = Path(__file__).parent
df = run_query(dn/'point-data.sql')

### Read images
datadir =project/'remote-data'
img = datadir/"drone-dem-07-Mar-2017/drone-dem/AmbergrisDEM_UTM19N.tif"

with rasterio.open(str(img),'r') as f:
    import IPython; IPython.embed()
### Find raster values at coordinates


### Do statistics

### Write back to database
